### ISSUE TITLE
Plugin failure: mrj-crosslink-between-notes Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by seb-mm** [mrjackphil/obsidian-crosslink-between-notes#1]
In the console it tells me that it couldn't find the `main.js`. You ship a `main.ts`.

Error message:
`app.js:1 Plugin failure: mrj-crosslink-between-notes Error: ENOENT: no such file or directory, open 'C:\Users\<path to my vault>\.obsidian\plugins\mrj-crosslink-between-notes\main.js'`

I put the extracted files in the folder you specified and I double-checked the path, so I don't know what could be the problem.

**Comment by mrjackphil** [comment]
Try to get files from [here](https://github.com/mrjackphil/obsidian-crosslink-between-notes/releases/latest)

**Comment by seb-mm** [comment]
Yes, I got them from there but downloaded the zip which was the sourcecode and not the package unlike other plugins. My bad!

Now it works like a charm!
