### ISSUE TITLE
A chance of data loss

### ISSUE THREAD

**Issue by lishid** [mrjackphil/obsidian-crosslink-between-notes#4]
https://github.com/mrjackphil/obsidian-crosslink-between-notes/blob/810f0936907da8b58666dcab7403a701dd1c439a/main.ts#L49

This is really really bad to use. `file.cachedData` is not guaranteed to exist, so there's a chance this will wipe the file.

We recommend reading the file from disk using `await vault.read(file)` anytime you're about to make modifications to a file. This reduces the chance of race conditions and guarantees that you will be using the latest file data.

I would highly recommend changing this line to:
```ts
await this.app.vault.modify(file, await this.app.vault.read(file) + `\n[[${fileName}]]`);
```

You will have to change the function to an async function though: https://github.com/mrjackphil/obsidian-crosslink-between-notes/blob/810f0936907da8b58666dcab7403a701dd1c439a/main.ts#L36

**Comment by lishid** [comment]
Also, highly recommend auto-formatting your code to normalize whitespace, and adding semicolons.
See here for why it's a good idea to add semicolons: https://stackoverflow.com/a/1169596

**Comment by mrjackphil** [comment]
@lishid Thank you so much for your feedback. I've put those changes in 0.0.2 release!

**Comment by lishid** [comment]
Great work as always!

**Comment by mrjackphil** [comment]
> Great work as always!

@lishid You are so kind. My fast dirty `code and publish` approach definitely needs to be revisited :) 

I didn't put semicolons, cause my current code base with which I'm currently working full-time has `no-semicolon` style-lint rule. But I'll keep that behavior in mind. Didn't know about it. 

Also, didn't know what you are monitoring and do code review for plugins :)

**Comment by lishid** [comment]
I usually only do a round of code review when a new plugin requests to be listed, but I also sometimes re-read when I get pinged for something about a plugin.
