### ISSUE TITLE
Would it be possible to extend the functionality to markdown links?

### ISSUE THREAD

**Issue by bergziege** [mrjackphil/obsidian-crosslink-between-notes#5]
Instead of Wiki-Links `[[xxx]]` I use markdown links `[xxx](../index.md)` for better html export compatibility.

Would it be possible to include the markdown link format into this addon?

**Comment by mrjackphil** [comment]
I believe it can be extended. It's just a matter of available time to dig into 😄 
I'll see what I can do when will have time.

**Comment by mrjackphil** [comment]
@bergziege I'm late for the party. But functionality was added. Now it adds links based on your preference in the settings menu (Editor -> Use [[Wikilinks]]). 

Feel free to reopen the issue if you have any problems.
