### ISSUE TITLE
suggestion: allow formatting for the pasted link

### ISSUE THREAD

**Issue by firinael** [mrjackphil/obsidian-crosslink-between-notes#6]
I use your plugin to add links to my index, and I like those links to be bulleted.

Would it be possible to add the option to format the links so that I can make my dream of having automatic bulleted links come true? Ideally you'd have a box in the plugin options where you could put the formatting around a {{linkedNote}} like so:
>  \- {{linkedNote}}

Thanks!

**Comment by mrjackphil** [comment]
I'll check what I can do.

**Comment by mrjackphil** [comment]
@firinael Hey, I've added a template feature. Please update the plugin and check the settings menu. Feel free to reopen the issue if you have any questions.
